cyverse-de/terrain

src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj
This change removes an endpoint that is not used any longer.
=> CORE-8062: removed the /apps/ids endpoint. which is not used

src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/core.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/comments.clj, src/terrain/services/metadata/internal_jobs.clj, src/terrain/util/config.clj
This change updates the pass-through endpoints in terrain to match the corresponding changes in apps.
=> Add the execution system ID to apps endpoints.

.gitignore, src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj
This is a relatively small change.
=> Update URI paths for several apps endpoints.

src/terrain/persistence/search.clj
=> Revert "CORE-8407: ES v5.0 Upgrade "

src/terrain/persistence/search.clj, src/terrain/util/config.clj
=> Extracted ES index to config property

src/terrain/routes/permanent_id_requests.clj, src/terrain/services/permanent_id_requests.clj
This PR adds link instructions to DOI completion notification comments, as requested by DC-103.
These instructions will not be included for ARK requests.
=> CORE-8934 Update user notification for DOI Request completion.

src/terrain/services/filesystem/stat.clj
Prevents potential `JargonException` "Unknown iRODS exception code recieved:-510024" in `GET /secured/favorites/filesystem` endpoint.
=> CORE-8949 Prevent potential "Too many open files" error.

LICENSE, project.clj
By request from Mary Margaret, I changed iPlant Collaborative references to CyVerse.
=> changed iPlant Collaborative references to CyVerse

src/terrain/clients/apps/raw.clj, src/terrain/clients/metadata/raw.clj, src/terrain/core.clj, src/terrain/routes/webhooks.clj
Add routing information.
`PUT` routing to `apps/webhooks`.
=> De 1129 de-webhooks terrain end-points

src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj, src/terrain/util/transformers.clj
This is a new endpoint to search for app categories by exact name.
=> CORE-9052: added the ability to search for app categories by name

src/terrain/clients/metadata/raw.clj, src/terrain/core.clj, src/terrain/routes/comments.clj, src/terrain/routes/favorites.clj, src/terrain/routes/tags.clj, src/terrain/services/metadata/comments.clj, src/terrain/services/metadata/favorites.clj, src/terrain/services/metadata/tags.clj
These new endpoints are intended primarily for use in the QA cleanup suite.
=> CORE-9067: metadata cleanup endpoints.

src/terrain/clients/search.clj, src/terrain/routes/search.clj, src/terrain/util/config.clj, terrain.properties.tmpl
(for data search only for now, of course)
This should be pretty straightforward? But, I want to make sure I'm still using best-practices since I haven't been doing much clojure lately.
=> Add a set of search service passthrough endpoints

src/terrain/auth/user_attributes.clj, src/terrain/clients/oauth.clj, src/terrain/util/oauth.clj
I'm going to merge this one immediately. Reviews are still welcome.
=> CORE-9250: modified terrain to accept OAuth tokens from CAS

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/comments.clj, src/terrain/routes/data.clj, src/terrain/routes/metadata.clj, src/terrain/routes/schemas/apps.clj, src/terrain/routes/token.clj, src/terrain/util.clj, src/terrain/util/transformers.clj
This PR will swaggerize the initial `/apps` endpoint docs, starting with just the `/apps` search endpoint for this PR.
If these initial PRs get approved, then the next PR will probably swaggerize docs for more than 1 `/apps` endpoint.
I also advise viewing this PR's diff with whitespace changes ignored.
=> CORE-11 Add apps listing swagger docs.

src/terrain/routes/schemas/collaborator.clj
I _think_ this will fix the issue with creating collaborator lists.  I tried testing it in swagger with my local changes and seemed ok.
=> Remove type as req key from AddCollaboratorListRequest

src/terrain/clients/analyses.clj, src/terrain/routes.clj, src/terrain/routes/analyses.clj
Adds swaggerized endpoints for quick launch favorites, user defaults, and global defaults. All of them are pass-thrus to the analyses service.
=> Quick Launches

src/terrain/clients/analyses.clj, src/terrain/routes/analyses.clj
This shouldn't be merged until https://github.com/cyverse-de/analyses/pull/2 has been merged.
=> Add /terrain/secured/quicklaunches/{ql-id}/app-info endpoint

src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/categories.clj, src/terrain/routes/metadata.clj
This PR will add the Swagger docs from cyverse-de/common-swagger-api#20 to the `GET /apps/communities/{community-id}/apps` endpoint.
=> CORE-11 Add GET /apps/communities/{community-id}/apps Swagger docs

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/reference_genomes.clj, src/terrain/routes/metadata.clj
This PR will add the Swagger docs for `/reference-genomes` endpoints added by cyverse-de/common-swagger-api#32.
=> CORE-11 Add Swagger docs for /reference-genomes endpoints.

src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/admin/tools.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/apps.clj
This PR will add the schemas and docs added by cyverse-de/common-swagger-api#39 to the `/admin/tools` endpoints.
=> CORE-11 Add Swagger docs to /admin/tools endpoints.

src/terrain/services/coge.clj, src/terrain/services/sharing.clj, src/terrain/util/service.clj, src/terrain/util/transformers.clj
This PR will remove some obsolete functions from `terrain.util.service` and `terrain.util.transformers`.
=> Remove some obsolete util functions.

src/terrain/clients/iplant_groups.clj, src/terrain/routes/schemas/user_info.clj, src/terrain/routes/user_info.clj
One more schema validation error fixed - I don't know why I originally added details to the path-params 😕
=> CORE-556 Fix query params for admin user info

project.clj, src/terrain/routes/analyses.clj
This PR will update the `POST /analyses` endpoint with the `coerce-analysis-submission-requirements` middleware added by cyverse-de/common-swagger-api#51.
Also reformats `terrain.routes.analyses` with `lein-cljfmt`.
=> CORE-468 Add coerce-analysis-submission-requirements middleware.

src/terrain/clients/dashboard_aggregator.clj, src/terrain/routes.clj, src/terrain/routes/dashboard_aggregator.clj
Modify the client and route for the dashboard calls to support being called by a logged out user.
=> Support dashboard requests while logged out

src/terrain/services/permanent_id_requests.clj
This PR will update DOI endpoints to continue processing DOI requests and creation if the source folder is already in the staging or publish directory.
This will allow DOI curators and admins to pre-move data folders into the staging or curated folders before processing DOI requests.
=> CORE-1045 Add temp workaround for async folder moves in DOI endpoints.

project.clj
Must wait for https://github.com/cyverse-de/common-swagger-api/pull/62 to be merged
=> CORE-1148 Bump common-swagger-api version

contribution-guidelines.md
Please feel free to make both content and style suggestions when reviewing this change.
=> CORE-1182: Contribution guidelines

src/terrain/auth/user_attributes.clj, test/terrain/test_fixtures.clj
These changes aren't related directly to [CORE-1226](https://cyverse.atlassian.net/browse/CORE-1226,) but I did notice the bug and use the improvement to `terrain.auth.user-attributes/with-user` when I was researching the issue.
=> CORE-1226: a bug fix and a miscellaneous testing improvement.

src/terrain/clients/app_exposer.clj, src/terrain/routes/instantlaunches.clj, src/terrain/routes/schemas/instantlaunches.clj
Adds support for instant launch metadata endpoints.
=> Add support for instant launch metadata endpoints

src/terrain/util/keycloak_oidc.clj
I think we could in theory improve this by decoding the JWT header to pull out a key ID and having the cached certs be keyed by that ID, and then only check against certs with a matching key ID. but it probably largely doesn't matter, especially since I think most of the time there's only one key in our use cases.
=> Cache JWKs for up to a day to avoid roundtrips to Keycloak

src/terrain/auth/user_attributes.clj, src/terrain/util/keycloak_oidc.clj
I think this is the basic stuff that's needed. It's not used anywhere yet, and I could use some recommendations if there's some endpoint I should add for testing or such.
Still, I think this is ready enough to be reviewed for the structure of the thing!
=> Start on adding Keycloak service account support to terrain

src/terrain/clients/data_usage_api.clj, src/terrain/middleware.clj, src/terrain/routes/data_usage_api.clj, src/terrain/routes/fileio.clj
Adds middleware to check for a data overage before allowing users to upload and save files through the DE.
=> Check data overage

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/apps/admin/apps.clj
This PR will add admin app version details and update endpoints.
=> CORE-1534 Add admin app version endpoints

src/terrain/clients/apps/raw.clj, src/terrain/routes/apps/admin/apps.clj
This PR will add `/admin/apps/sharing` and `/admin/apps/unsharing` endpoints.
=> CORE-1533 Add admin sharing endpoints

src/terrain/clients/qms.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj
Here's the Swagger documentation for the endpoint:
Here's an example usage:
```
$ curl -sH "$AUTH_HEADER" "http://localhost:8000/terrain/admin/qms/subscriptions?limit=3&search=sarahr&sort-field=end-date&sort-dir=DESC" | jq
{
"result": {
"subscriptions": [
{
"id": "1c7a9cca-69fe-11ed-8978-62d47aced14b",
"effective_start_date": "2022-11-21T17:39:23.854474-07:00",
"effective_end_date": "2023-11-21T17:39:23.854474-07:00",
"user": {
"id": "cd7b20f2-03bb-11ed-b868-62d47aced14b",
"username": "sarahr"
},
"plan": {
"id": "d80b5482-98dc-11ec-bbe3-406c8f3e9cbb",
"name": "Commercial",
"description": "Commercial plan",
"plan_quota_defaults": [
{
"id": "1e3804ed-4ed3-4cd9-8e58-1e725fa79c1b",
"quota_value": 5000,
"resource_type": {
"id": "99e3bc7e-950a-11ec-84a4-406c8f3e9cbb",
"name": "cpu.hours", …
```
=> CORE-1807: added the subscription listing endpoint

project.clj, src/terrain/routes/schemas/filesystem.clj, src/terrain/services/sharing.clj
Depends on cyverse-de/common-swagger-api#83
Doesn't currently include analysis sharing. I'll do that next.
=> Group data sharing

k8s/terrain.yml, project.clj, src/terrain/core.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj, src/terrain/routes/schemas/resource_usage_api.clj, src/terrain/services/qms.clj, src/terrain/util/config.clj, src/terrain/util/nats.clj, src/terrain/util/time.clj
This PR adds endpoints for listing and adding add-ons will be applicable to subscriptions.
As part of this PR, support for posting requests to NATS was added along with support for using the Java classes generated from the protocol buffer definitions in the https://github.com/cyverse-de/p/ repository.
=> CORE-1841, CORE-1842: Add endpoints for listing and adding add-ons

project.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj, src/terrain/services/qms.clj, src/terrain/util/config.clj
Adds endpoint for modifying an available add-on. 
Make sure that the following are merged first:
* https://github.com/cyverse-de/terrain/pull/265
* https://github.com/cyverse-de/subscriptions/pull/6
=> CORE-1843: Adds support for modifying an available add-on

project.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj, src/terrain/services/qms.clj, src/terrain/util/config.clj
Adds support for deleting an add-on based on its UUID.
Make sure that following PRs are merged before this one:
* https://github.com/cyverse-de/terrain/pull/265
* https://github.com/cyverse-de/subscriptions/pull/7
=> CORE-1844: Add support for deleting an add-on

src/terrain/routes/qms.clj
The cyverse-subscription-updater service account needs to be able to do the following:
* Get a user’s subscription ID from the plan endpoint.
* List available add-ons.
* Add an add-on to a subscription.
* Delete an add-on from a subscription.
* Update an add-on applied to a subscription.
* List add-ons applied to a subscription.
* Get information about a single add-on applied to a subscription.
This should not change the other endpoint(s) already available to the same service account.
JIRA: https://cyverse.atlassian.net/browse/CORE-1878
=> CORE-1878: Add service account accessible subscription add-on endpoints

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/apps/admin/tools.clj, src/terrain/routes/apps/tools.clj
(depends on cyverse-de/common-swagger-api#84 and this branch will be updated to non-snapshot before merge)
=> Pass through parameters for tool details requests so include-defaults comes through

src/terrain/util/config.clj
Unsure it's that likely we'll pass in @ signs, but may as well remove them if we do, since the other code assumes there won't be one.
=> Trim leading @ off the UID domain, just in case

src/terrain/clients/apps/raw.clj, src/terrain/clients/keycloak/admin.clj, src/terrain/services/bootstrap.clj, src/terrain/util/config.clj
This uses a keycloak admin API client to fetch the user's current session(s) from there and pass the information down to apps for storing in the database.
There is one TODO in the code but I think this can be reviewed without fixing it for now.
=> Fetch login info (IP, session ID) from Keycloak for recording in the DE database

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/callbacks.clj
This PR will add updates for cyverse-de/common-swagger-api#85, which must be merged first before this PR can be merged.
=> CORE-1997 Replace /callbacks/agave-job with /callbacks/tapis-job

src/terrain/clients/apps/raw.clj, src/terrain/routes/bootstrap.clj, src/terrain/routes/schemas/bootstrap.clj
For use in displaying a table of recent logins in the DE
=> Logins endpoint

skaffold.yaml, src/terrain/clients/qms_nats.clj
This was simply a code change that should have made but wasn't.
=> CORE-2016: fixed a bug that was preventing addon rates from being updated.

src/terrain/routes.clj, src/terrain/routes/fileio.clj, src/terrain/routes/filesystem.clj, src/terrain/services/fileio/controllers.clj, src/terrain/services/filesystem/updown.clj
I think this is all that's needed, but I can't really test this locally because NATS certificates are a pain. So close reviews are definitely welcome.
=> Allow unauthenticated file downloads to download as the anonymous user

project.clj, src/terrain/routes/bootstrap.clj, src/terrain/routes/schemas/bootstrap.clj
ref: cyverse-de/common-swagger-api#89
=> Use ListLoginsResponse from common-swagger-api rather than one only here
