cyverse-de/terrain

project.clj
Update versions for compojure-api and some of its dependencies.
Currently compojure-api is only used to wrap exception handling in terrain, so no routes had to be updated.
=> CORE-8178 Update compojure-api version to 1.1.8

src/terrain/clients/data_info.clj, src/terrain/clients/data_info/raw.clj, src/terrain/routes/metadata.clj, src/terrain/services/bootstrap.clj, src/terrain/services/metadata/apps.clj, src/terrain/services/user_prefs/output_dir.clj
The current `GET /secured/bootstrap` endpoint response has the following structure:
```json
{
"loginTime": "1374190755304",
"newWorkspace": false,
"workspaceId": "4",
"username": "snow-dog",
"full_username": "snow-dog@iplantcollaborative.org",
"email": "sd@example.org",
"firstName": "Snow",
"lastName": "Dog",
"userHomePath": "/iplant/home/snow-dog",
"userTrashPath": "/iplant/trash/snow-dog",
"baseTrashPath": "/iplant/trash",
"preferences": {
"systemDefaultOutputDir": {
"id": "/iplant/home/snow-dog/analyses",
"path": "/iplant/home/snow-dog/analyses"
},
"defaultOutputFolder": {
"id": "/iplant/home/snow-dog/analyses",
"path": "/iplant/home/snow-dog/analyses"
}
},
"auth-redirect": {
"example": "https://example.org"
}
}
```
These fields are pieced together from 3 different services other than …
=> CORE-7813 Reorganize /secured/bootstrap response

src/terrain/clients/user_prefs.clj, src/terrain/services/bootstrap.clj
This PR includes fixes in the `/bootstrap` endpoint for parsing error responses from the apps and preferences services when they are under maintenance (503 or 504 responses).
=> CORE-8446 Fix /bootstrap error encoding.

src/terrain/routes/oauth.clj
The UI typically is informed of any redirect uris via the bootstrap endpoint.  Exposing this will allow the UI an opportunity to retrieve those uris outside of bootstrap.
=> CORE-8443 Provide passthrough to apps for redirect uris

src/terrain/persistence/search.clj
This PR contains updates to the terrain service to ensure that it's search features are API compatible with ES v5.0. The list below describes the [API Breaking Changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.0.html) which were fixed as part of this PR.
=> CORE-8407: ES v5.0 Upgrade 

src/terrain/persistence/search.clj, src/terrain/services/search.clj
This PR contains updates to the terrain service to ensure that it's search features are API compatible with ES v5.0. The list below describes the [API Breaking Changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.0.html) which were fixed as part of this PR.
=> CORE-8407: ES v5.0 Upgrade

src/terrain/services/filesystem/directory.clj
This should make paged-directory properly mark data-info as down with the new UI resiliency stuff.
=> For 503s when calling data-info in paged-directory, rethrow as another 503

src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/apps.clj
The following apps service endpoint passthroughs have been added:
* `GET /admin/tools`
* `GET /admin/tools/:tool-id`
* `POST /tools`
* `POST /tools/permission-lister`
* `POST /tools/sharing`
* `POST /tools/unsharing`
* `DELETE /tools/:tool-id`
* `PATCH /tools/:tool-id`
Also the `public` parameter is now allowed with the `GET /tools` endpoint.
=> CORE-8720 Add new apps endpoints for private tools.

src/terrain/clients/iplant_groups.clj, src/terrain/routes/collaborator.clj, src/terrain/services/collaborator_lists.clj
This change adds `GET /collaborator-lists/:name` and `DELETE /collaborator-lists/:name` endpoints. It also changes the endpoints so that they don't try to create the Grouper folder that is used for collaborator lists unless that folder actually has to be present. For the time being, the only endpoint that has to ensure that the folder exists is the endpoint that adds a new collaborator list. I believe that this is the only endpoint that will have to ensure that the folder exists, but I'm not willing to commit to that statement completely at this time.
I'm hoping that preventing multiple endpoints from trying to create the folder will eliminate a concurrency issue that we were encountering when the listing and addition endpoints were called at about the same time. We may still encounter …
=> CORE-8800: get and delte endpoints for specific collaborator lists.

src/terrain/clients/iplant_groups.clj, src/terrain/core.clj, src/terrain/routes/collaborator.clj, src/terrain/services/teams.clj
Example team creation:
```
$ curl -sH "$AUTH_HEADER" -H "Content-Type: application/json" -d '{"name":"aqua-team","description":"mah team description","public_privileges":["view","optin"]}' "http://localhost:8080/teams" | jq .
{
"description": "mah team description",
"name": "dennis:aqua-team",
"type": "group",
"extension": "aqua-team",
"id": "230705b9ee8a40fa80c12bc2a1ba2efc",
"display_extension": "aqua-team",
"display_name": "iplant:de:de-2:teams:dennis:aqua-team",
"id_index": "11104"
}
```
Team listings can be filtered by `creator` (the username of the user who created the team), `member` (the username of a member of the group--only groups containing that user will be listed), and `search` (a partial group name search). Grouper doesn't provide a group name search when searching for …
=> Added endpoints to create and list teams.

src/terrain/clients/iplant_groups.clj, src/terrain/routes/collaborator.clj, src/terrain/services/teams.clj
This change adds endpoints to add, remove, and list team members. It also adds an extra validation step to several existing endpoints to ensure that a 404 is returned if someone tries to update a team that doesn't exist.
=> Team Membership Endpoints

project.clj, src/terrain/clients/iplant_groups.clj, src/terrain/clients/permissions.clj, src/terrain/routes/collaborator.clj, src/terrain/services/collaborator_lists.clj
This change allows users to grant the permissions that had been granted to a collaborator list directly to be granted to members that are removed from a collaborator list or to all collaborator list members if the collaborator list is being deleted.
Update: I had some other minor changes to the subject search endpoint that were finished shortly after I submitted this PR. Rather than create a new branch and a new PR, I just included these changes with this PR.
=> Collaborator List Permission Retention

src/terrain/clients/iplant_groups.clj
This change only applies if a team administrator tries to remove themselves using the POST /teams/:team-name/members/deleter endpoint. The POST /teams/:team-name/leave endpoint will still work because it uses the configured Grouper admin user to update the team privileges.
=> CORE-8986: allow administrative users to remove themselves from a team

src/terrain/clients/notifications.clj, src/terrain/services/teams.clj
The primary purpose of this PR is to notify users when they have been added to a team. A minor modification to the team join request notification was also required.
=> Team notification updates.

src/terrain/services/permanent_id_requests.clj, src/terrain/util/email.clj
This PR will update the DOI request and creation functions so that errors from the `data-info` service will now be caught, data admins will be emailed about the error, and the DOI request/creation process can continue successfully.
This PR depends on cyverse-de/iplant-email#5
=> CORE-9169 Email data admins when DOI data folder could not be moved.

src/terrain/clients/iplant_groups.clj
I'm going to be evil and merge this change immediately. Reviews are still welcome.
=> CORE-9263: prevent de_grouper from showing up in subject searches

src/terrain/clients/iplant_groups.clj, src/terrain/clients/notifications.clj, src/terrain/core.clj, src/terrain/routes/collaborator.clj, src/terrain/services/communities.clj, src/terrain/services/teams.clj
This PR will add `/communities` endpoints for App Community CRUD and admin management for #71.
These changes mainly modify the existing teams functions for creating groups as either `iplant:de:<env>:teams:<user>:<name>` or `iplant:de:<env>:communities:<name>`.
New Communities will be publicly viewable by default, with the creator as the initial admin, but an endpoint is available for adding or removing additional admins.
=> Add `/communities` endpoints for App Community management.

src/terrain/core.clj, src/terrain/routes/collaborator.clj, src/terrain/services/communities.clj
This PR will add `/admin/communities` endpoints for admin App Community management for #71.
These admin endpoints just reuse the regular functions used by the `/communities` endpoints, except they act as the DE grouper user to ensure they always have admin permissions for each action.
The 1 exception to this is `POST /admin/communities`, which will still add the new community as the requesting user, automatically adding them as an admin to that community.
=> Add `/admin/communities` endpoints for admin App Community management.

project.clj, src/terrain/clients/datacite.clj, src/terrain/clients/ezid.clj, src/terrain/routes/permanent_id_requests.clj, src/terrain/services/permanent_id_requests.clj, src/terrain/util/config.clj
This PR will update the `/permanent-id-requests` endpoints with a DataCite client for DOI submissions in order to support duplicated and nested metadata AVUs.
Since EZID is being discontinued, these endpoints have also been updated for DOI submission requests to [DataCite's EZ API](https://support.datacite.org/docs/datacite-ez-api-guide) (also requires updating the endpoints and credentials in terrain's configs).
This PR also adds a `GET /permanent-id-requests/:request-id/preview-submission` endpoint for previewing the DataCite XML, generated from folder metadata, that would be submitted to DataCite for DOIs.
Note that `terrain.clients.datacite` was written before work was done for https://github.com/cyverse-de/metadata-files.
This PR contains the minimal required for generating DataCite …
=> CORE-8699 Update /permanent-id-requests endpoints with DataCite client for DOI submissions

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/clients/iplant_groups.clj, src/terrain/clients/metadata/raw.clj, src/terrain/routes/collaborator.clj, src/terrain/services/communities.clj, src/terrain/services/permanent_id_requests.clj, src/terrain/util/config.clj
This PR will update `PATCH /(admin/)communities/{name}` to check for apps tagged in that community when the admin is renaming that community, by adding `retag-apps` and `force-rename` params to these endpoints, so that when these params are omitted (or set to `false`) when renaming the community, an `ERR_EXISTS` will be thrown if any apps are tagged. Otherwise, any app AVU tags will be updated with the new community name if the `retag-apps` param is set to `true`.
This PR also updates some `terrain.clients.metadata.raw` functions with cyverse-de/metadata-client@3.0.1 and an optional `terrain.communities.metadata.attr` config.
=> Check for tagged apps when renaming a community.

src/terrain/clients/iplant_groups.clj, src/terrain/routes/collaborator.clj, src/terrain/services/communities.clj
This PR will add `/communities/:name/members`, `/communities/:name/join`, and `/communities/:name/leave` endpoints.
The `/communities/:name` endpoint already supports the `?member=username` query param.
The current plan for these endpoints is to allow a user to "favorite" a community by becoming a member, and have only their "favorite" communities listed in the Apps window by the UI (via the `/communities/:name?member=username` endpoint).
=> Add `/communities/:name/members`, `join`, and `leave` endpoints.

src/terrain/services/communities.clj
Was wondering why I couldn't join any communities where I wasn't an admin 😄 I _think_ this is the only spot where it's needed.
=> Add public optin privileges when creating a community

project.clj, src/terrain/clients/analyses.clj, src/terrain/routes.clj, src/terrain/routes/analyses.clj, src/terrain/util/config.clj
Adds the secured facade endpoints for the new analyses service. All of the endpoints are swaggerized.
A new configuration option `terrain.analyses.base-uri` has been added with a sane default that should work inside our kubernetes clusters.
=> Analyses facade

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/elements.clj, src/terrain/routes/metadata.clj
Added `terrain.routes.apps.elements`, which is basically the same as `apps.routes.apps.elements`, except the potentially obsolete `GET /apps/elements/tools` endpoint has been omitted for now.
=> CORE-11 Add /apps/elements swagger docs.

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj
I decided not to add Swagger docs to terrain for this endpoint just yet because that would probably involve a switch to compojure-api version 1.1.12, which would take more time.
=> CORE-148: added the GET /analyses/:analysis-id/history endpoint

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj
Added swagger docs for `/apps/shredder`, `permission-lister`, `sharing`, and `unsharing` endpoints.
Note that this PR can't be merged until the `common-swagger-api.schema.badges` schemas are replaced with `common-swagger-api.schema.quicklaunches` schemas from `common-swagger-api` v2.10.3.
Then the changes in cyverse-de/common-swagger-api#14 can be versioned on top of `common-swagger-api` v2.10.3, and this PR will be updated with that newer version.
=> CORE-11 Add some /apps endpoint swagger docs.

project.clj
Oops! I just realized that `lein eastwood` was reporting arity problems with elastisch version 3.0.0.
=> CORE-8: switched back to eastisch version 2.2.0

project.clj, src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/comments.clj, src/terrain/services/metadata/internal_jobs.clj
This PR will add the Swagger docs from endpoints in `apps.routes.app` (migrated in cyverse-de/apps#154) to endpoints in `terrain.routes.metadata`.
=> CORE-11 Add Swagger docs from apps.routes.app to terrain.routes.metadata

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/pipelines.clj, src/terrain/routes/metadata.clj
This PR will add the Swagger docs migrated in cyverse-de/apps#155 and cyverse-de/common-swagger-api#16 to terrain's `/apps/pipelines` endpoints.
=> CORE-11 Add Swagger docs to /apps/pipelines endpoints

src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/categories.clj, src/terrain/routes/metadata.clj, src/terrain/routes/schemas/categories.clj
This PR will add Swagger docs to `/apps/categories` endpoints with the schemas and docs from cyverse-de/common-swagger-api#17
=> CORE-11 Add Swagger docs to /apps/categories endpoints

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/categories.clj, src/terrain/routes/metadata.clj, src/terrain/routes/schemas/categories.clj
This PR will add Swagger docs to `/apps/hierarchies` endpoints with the docs and schemas migrated in cyverse-de/common-swagger-api#18.
=> CORE-11 Add Swagger docs to /apps/hierarchies endpoints

project.clj, src/terrain/routes/apps/categories.clj, src/terrain/routes/metadata.clj
This PR will use `common-swagger-api` v2.10.7 doc strings that replaced markdown docs, and `common-swagger-api.schema.ontologies` response schemas added by cyverse-de/common-swagger-api#19.
=> CORE-11 Remove `Delegates to metadata service` sections from apps docs

src/terrain/routes.clj, src/terrain/routes/analyses.clj
These are some minor changes to remove the `/secured` context from the quicklaunch routes and to add a tag description for them.
=> Minor changes to quicklaunch endpoints.

src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/metadata.clj, src/terrain/routes/metadata.clj
This PR will add Swagger docs and schemas added by cyverse-de/common-swagger-api#21 to `/apps/{app-id}/metadata` endpoints.
=> CORE-11 Add Swagger docs to /apps/{app-id}/metadata endpoints

src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/communities.clj, src/terrain/routes/metadata.clj
This PR will add Swagger docs added by cyverse-de/common-swagger-api#22 to `/apps/{app-id}/communities` endpoints.
=> CORE-11 Add Swagger docs to /apps/{app-id}/communities endpoints

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/elements.clj, src/terrain/routes/apps/tools.clj, src/terrain/routes/metadata.clj
This PR will add the Swagger docs added by cyverse-de/common-swagger-api#23 to the `/tools` endpoints.
=> CORE-11 Add Swagger docs to /tools endpoints

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/analyses.clj, src/terrain/routes/metadata.clj
This PR will add the Swagger docs added by cyverse-de/common-swagger-api#24 to the `/analyses` endpoints.
=> CORE-11 Add Swagger docs to /analyses endpoints

project.clj, src/terrain/clients/apps.clj, src/terrain/services/metadata/internal_jobs.clj
This PR will:
* Update `terrain.services.metadata.internal-jobs/launch-url-import-job` to use `terrain.clients.apps.raw/submit-job`.
* Remove the obsolete `terrain.clients.apps/submit-job` function.
* Bump `common-swagger-api` dependency to version `2.11.4`, which includes a fix from cyverse-de/common-swagger-api#27 that added paging params to the `/tools` endpoint.
=> CORE-11 Fixes for URL import and tool search endpoints

project.clj, src/terrain/routes/apps/tools.clj
This PR will add the `coerce-tool-import-requests` middleware, added by cyverse-de/common-swagger-api#28, to the add and update `/tools` endpoints.
Missed in #107.
=> CORE-11 Add coerce-tool-import-requests middleware to /tool endpoints.

src/terrain/routes.clj, src/terrain/routes/schemas/user_info.clj, src/terrain/routes/user_info.clj, src/terrain/services/user_info.clj
Also removed the `/user-search` endpoint since the UI uses the `/subjects` for searching instead.
=> CORE-20 Add swagger docs for user-info endpoints

project.clj, src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/bootstrap.clj, src/terrain/routes/metadata.clj, src/terrain/routes/schemas/bootstrap.clj, src/terrain/routes/schemas/user_prefs.clj, src/terrain/services/bootstrap.clj, src/terrain/services/metadata/apps.clj, src/terrain/services/user_prefs.clj, src/terrain/services/user_prefs/output_dir.clj
This PR will use the Swagger docs added by cyverse-de/common-swagger-api#30 for the `/bootstrap` and `/logout` endpoints.
Also includes a fix for the `logout` endpoint to prevent terrain's middleware from stripping the required `ip-address` param.
=> CORE-11 Add Swagger docs to bootstrap and logout endpoints.

project.clj, src/terrain/clients/apps.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/tools.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/apps.clj
This PR will add the schemas and docs added by cyverse-de/common-swagger-api#31 to to `/tool-requests` endpoints.
This requires refactoring the `username` extraction and `send-tool-request-email` call out of `terrain.services.metadata.apps/postprocess-tool-request` and into `submit-tool-request`.
=> CORE-11 Add Swagger docs to /tool-requests endpoints.

src/terrain/routes/schemas/search.clj
I missed this when reviewing the original PR, but these are also things that can be passed! Scroll sets a timeout, but as a string (e.g. "1m" for one minute), and if a scroll timeout is provided the response will include a scroll_id. Then, subsequent requests can get more results from the same search by passing back the scroll ID. This is pretty much the same as the underlying ES stuff, and it was added for the use case of pulling down the ES representations of a bunch of things at once.
Since in the case of a scroll_id being passed the query isn't, now every key is marked optional, but, alas.
=> Add support for scroll and scroll_id to this facade

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/admin/apps.clj, src/terrain/routes/metadata.clj, src/terrain/routes/schemas/admin.clj
This PR will add the Swagger docs added by cyverse-de/common-swagger-api#33 to `/admin/apps` endpoints.
It will also refactor `terrain.routes.metadata/admin-apps-routes` into a new `terrain.routes.apps.admin.apps` namespace.
=> CORE-11 Add Swagger docs for /admin/apps endpoints.

src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/admin/reference_genomes.clj, src/terrain/routes/metadata.clj, src/terrain/services/metadata/apps.clj
This PR will add the Swagger docs, added by cyverse-de/common-swagger-api#34, to `/admin/reference-genomes` endpoints.
=> CORE-11 Add Swagger docs to /admin/reference-genomes endpoints

project.clj, src/terrain/routes/schemas/admin.clj
This PR will refactor App job stats start/end date params as Strings, using params added by cyverse-de/common-swagger-api#35, since `Date` query params are parsed into invalid string formats (`Tue Dec 30 17:00:00 MST 1969` for example) when forwarded to the apps service.
=> CORE-11 Refactor terrain.routes.schemas.admin/AdminAppSearchParams

src/terrain/clients/data_info.clj, src/terrain/services/bootstrap.clj, src/terrain/services/teams.clj, src/terrain/util/service.clj
This PR will update a few hold-out namespaces in terrain to use `clojure-commons.assertions` so that the duplicate assertions in `terrain.util.service` can be removed.
It will also remove other obsolete functions in `terrain.util.service` that are no longer in use.
=> Remove some obsolete terrain.util.service functions.

project.clj, src/terrain/routes.clj, src/terrain/routes/filesystem.clj, src/terrain/routes/filesystem/navigation.clj, src/terrain/routes/schemas/filesystem/navigation.clj, src/terrain/services/filesystem/directory.clj, src/terrain/services/filesystem/root.clj
This PR will use the docs and schemas added by cyverse-de/common-swagger-api#41 in the `/filesystem/root` and `/filesystem/directory` endpoints.
These endpoints still need to be moved into a `filesystem` tagged context, so they don't stay in the `default` group of the Swagger UI. So this PR is marked as a `WIP` for now.
=> CORE-9 Add Swagger docs to filesystem navigation endpoints

src/terrain/clients/data_info.clj, src/terrain/routes.clj, src/terrain/routes/filesystem.clj, src/terrain/routes/filesystem/exists.clj
This PR will add the schemas and docs from cyverse-de/common-swagger-api#43 to the `POST /secured/filesystem/exists` endpoint.
=> CORE-9 Add Swagger docs to path existence endpoint.

src/terrain/services/permanent_id_requests.clj, src/terrain/util/email.clj
This PR will update the DOI completion notification message (sent to the requesting user) to include additional user instructions and the DOI's landing page link.
It will also include the created DOI in curator completion email template values (support added in cyverse-de/iplant-email#8).
=> CORE-331 Update DOI completion notification message.

project.clj, src/terrain/clients/data_info.clj, src/terrain/clients/data_info/raw.clj, src/terrain/routes.clj, src/terrain/routes/filesystem.clj, src/terrain/routes/filesystem/tickets.clj, src/terrain/routes/schemas/filesystem/tickets.clj
This PR will add the Swagger docs from cyverse-de/common-swagger-api#49 to the filesystem ticket endpoints.
=> CORE-9 Add Swagger docs to filesystem ticket endpoints.

project.clj, src/terrain/clients/data_info.clj, src/terrain/clients/data_info/raw.clj, src/terrain/routes.clj, src/terrain/routes/filesystem.clj, src/terrain/routes/filesystem/stats.clj, src/terrain/services/filesystem/stat.clj
This PR will add the schemas and docs added by cyverse-de/common-swagger-api#52 to the  `filesystem/stat` endpoint.
The `terrain.routes` namespace was also reformatted with `lein-cljfmt`
=> CORE-9 Add Swagger docs to the filesystem stat endpoint.

src/terrain/services/permanent_id_requests.clj
and, rely on the share function afterwards to ensure permissions for the DOI curators group
This sets it up so we can change data-info to pass a client user when doing moves and renames, as requested by @tedgin
=> Use de-irods to move folders for permanent ID requests

src/terrain/clients/dashboard_aggregator.clj, src/terrain/routes.clj, src/terrain/routes/dashboard_aggregator.clj, src/terrain/routes/schemas/dashboard_aggregator.clj, src/terrain/services/dashboard_aggregator.clj, src/terrain/util/config.clj
Adds an authenticated endpoint called `/secured/dashboard` that passes requests along to the `/users/:username` endpoint of the dashboard-aggregator service. The intention is to use it to get information for the dashboard in Sonora.
The data included now isn't complete, this is intended to get the plumbing in place for future work.
=> Dashboard-related endpoint

src/terrain/routes/schemas/dashboard_aggregator.clj
The backing service, dashboard-aggregator, now supports returning info from the news and events RSS feeds on the CyVerse website, so the schema in Terrain needs to be modified to accommodate them.
=> Add the dashboard feeds to the schema for the dashboard endpoint

project.clj, src/terrain/clients/analyses.clj, src/terrain/clients/requests.clj, src/terrain/routes.clj, src/terrain/routes/requests.clj, src/terrain/routes/schemas/requests.clj, src/terrain/routes/settings.clj, src/terrain/services/requests.clj, src/terrain/util/config.clj
This PR adds several routes that can be used to allow users to submit VICE access requests and view the requests that they've submitted. It also adds administrative routes for requests and concurrent job limits.
There's a bit of an inconsistency between the way that the administrative and non-administrative request routes are defined. The non-administrative routes are explicitly defined for each type of request (currently, there's only one type of request: `vice`). The administrative routes are written to handle multiple different types of requests instead. The reason for this is that it's convenient to be able to specify the `detail` fields that are required for each request in the non-administrative endpoints. In the administrative endpoints, the details are never changed, so we can …
=> CORE-675 - requests and concurrent job limit routes

src/terrain/clients/dashboard_aggregator.clj, src/terrain/routes/dashboard_aggregator.clj
Refactors the dashboard-aggregator client and route so the limit query parameter gets passed down to the dashboard-aggregator service.
Tested locally, both logged in and logged out. Appears to be working as intended.
=> Ensure limit param gets passed through to backing service

src/terrain/clients/app_exposer.clj, src/terrain/routes.clj, src/terrain/routes/schemas/vice.clj, src/terrain/routes/vice.clj
Adds an admin-only proxy endpoint at /admin/vice/resources in Terrain to app-exposer's /vice/listing endpoint.
By default it will list deployments, services, ingresses, configmaps, and pods for all running VICE analyses in the cluster. You can filter based on different fields, none of which are required.
Right now all of the requests are read-only. Future updates will allow for terminating and possibly editing resources.
=> Add VICE admin UI endpoints to Terrain

src/terrain/clients/app_exposer.clj, src/terrain/routes/schemas/vice.clj, src/terrain/routes/vice.clj
Adds administrative endpoints for managing VICE analyses. Provides endpoints for getting and extending the time limit, triggering save-and-exit, and getting async data (IP addr, Analysis UUID, and subdomain).
These differ from the existing endpoints in that they require the logged in user to have administrative permissions and allows them to perform operations on VICE analyses submitted by normal users.
=> Add routes to manage VICE analyses

src/terrain/clients/app_exposer.clj, src/terrain/routes/vice.clj
When I modified the time-limit endpoints (non-admin), I accidentally broke them by attempting to manually set the username in the requests, rather than just using the shortUsername of the logged in user. This resulted in errors popping up in QA. This PR should fix them.
=> Fix arity errors in the time limit endpoints

src/terrain/clients/app_exposer.clj, src/terrain/routes/schemas/vice.clj, src/terrain/routes/vice.clj
This PR changes the VICE time-limit endpoints to use the new admin versions in app-exposer (which takes the analysisID instead of the externalID) along with adding the following VICE admin endpoints
* POST /vice/analyses/:analysisID/save-and-exit
* POST /vice/analyses/:analysisID/exit
* POST /vice/analyses/:analysisID/save-output-files
* POST /vice/analyses/:analysisID/download-input-files
* GET /vice/analyses/:analysisID/external-id
=> Add new VICE admin endpoints

src/terrain/routes/schemas/vice.clj
A couple of the fields in the VICE schema cause issues in the admin UI when they're not optional. This PR should fix that.
=> Make :containerID and :message fields optional

resources/docs/get-admin-token.md, resources/docs/get-token.md, src/terrain/clients/keycloak.clj, src/terrain/routes.clj, src/terrain/routes/schemas/token.clj, src/terrain/routes/token.clj, src/terrain/services/oauth.clj, src/terrain/util/config.clj
This PR finally adds the ability for administrators to impersonate users without having to run terrain locally and jump through a bunch of hoops. The administrative token endpoints use HTTP basic authentication, and they don't do any authorization checks themselves. Instead, they pass the information to Keycloak and allow Keycloak to do the validation. The drawback to this approach is that it means that we'll have to maintain administrative privileges for impersonation tokens separately through Keycloak. The advantage is that we can be more selective about which users have the ability to impersonate other users.
=> CORE-1027: allow administrators to impersonate users for troubleshooting

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes/analyses.clj
I timed the analyses listing endpoint before and after adding the status counts, based on production data for Tyson since I figure he's an active user.  Looks like there's no significant change to adding the status counts.
Before:
"Elapsed time: 11405.267379 msecs"
"Elapsed time: 11353.308928 msecs"
"Elapsed time: 10605.780889 msecs"
After:
"Elapsed time: 11938.507988 msecs"
"Elapsed time: 11914.46379 msecs"
"Elapsed time: 10687.588213 msecs"
=> CORE-600 Add analyses job status endpoint, and status count to analyses listing

src/terrain/clients/data_info.clj, src/terrain/clients/data_info/raw.clj, src/terrain/services/permanent_id_requests.clj
This change updates the permanent ID request listing endpoints to retrieve stat information for the folders corresponding to all of the permanent ID requests at once, which should dramatically improve the responsiveness of the endpoint. In  my local testing, the endpoint took a little over 20 seconds to respond. If we need further responsiveness improvements later, we can add pagination or allow the caller to filter the results.
**Note:** The endpoint to get a single permanent ID request is currently not working. We're getting an error in the metadata service that's preventing the request from succeeding. I've created a Jira issue (CORE-1099) for this. I'm hoping to get this change merged before that problem is fixed, however, because this change should allow the permanent ID request …
=> CORE-1097: speed up the permanent ID request listing endpoints.

src/terrain/routes/filesystem.clj, src/terrain/services/filesystem/directory.clj, src/terrain/services/filesystem/root.clj
The main request from the ticket was to have the root listing return all 4 roots (home, shared with me, community data, trash) even for logged out users.  On top of that, logged out users needed to get a 401 if they tried to navigate to (i.e. get a paged directory listing for) any root other than community data, so that work is also in this PR.
=> CORE-1031 Allow logged out users to get root listing and view community data

src/terrain/routes.clj, src/terrain/routes/filesystem/navigation.clj
This effectively creates GET /filesystem/roots which can be used without auth, but still allows GET /secured/filesystem/roots to work as usual.
This means for Sonora to pick up the changes, it will have to be updated to hit the non-secured route.
=> CORE-1031 Add filesystem roots to optionally-authenticated-routes

src/terrain/routes/schemas/dashboard_aggregator.clj
Adds the content and author fields to the dashboard feed items schema and adds the video feed to the dashboard feeds schema.
Depends on https://github.com/cyverse-de/dashboard-aggregator/pull/1, they should probably be merged at the same time.
=> Dashboard schema updates

project.clj, src/terrain/clients/async_tasks.clj, src/terrain/services/permanent_id_requests.clj, src/terrain/util/config.clj
This PR will add async folder move support to DOI Request endpoints.
Currently the DOI Request endpoints are trying to move the user's folder to the staging or curated directory as the irods proxy user, and then immediately share the moved folder with the DOI curators group using the destination path, which doesn't exist yet since the async task service takes a few seconds to perform the move.
This PR updates these endpoints to spawn a thread that polls the async tasks service until the async move is complete, and then the thread will update the permissions on the moved folder. In the meantime the DOI request or creation will continue as normal while the move happens in the background.
If the move fails for any reason, the permissions will still be updated on the source folder so the DOI …
=> CORE-1045 Add async folder move support to DOI Request endpoints.

src/terrain/clients/bags.clj, src/terrain/routes.clj, src/terrain/routes/bags.clj, src/terrain/routes/schemas/bags.clj, src/terrain/services/bags.clj, src/terrain/util/config.clj
Add routes, a service, a client, and configuration values for bag-related endpoints. The routes are swaggerized.
Fixes the default values for the sessions, preferences, and saved-searches config settings so they hit user-info.
=> Bag support

src/terrain/clients/bags.clj, src/terrain/routes/bags.clj, src/terrain/routes/schemas/bags.clj, src/terrain/services/bags.clj
Adds support for default bag handling, which allows callers to ignore the multiple bag support if they so wish.
This is dependent on https://github.com/cyverse-de/user-info/pull/5 getting merge.
=> Add Default Bag Support

src/terrain/clients/bags.clj, src/terrain/routes/bags.clj
Depends on https://github.com/cyverse-de/user-info/pull/6 being merged.
Updates the expected return values for default bag operations to always return the new state of the bag. Specifically done for integration with react-query, but it's a practice that I should have done in the first place regardless.
=> Fix default bag returns

src/terrain/routes/schemas/dashboard_aggregator.clj
This change adds `recentlyUsed` to the response body schema for the dashboard endpoint. It also adds a new optional query parameter, `start-date-interval`, to the same endpoint.
=> CORE-1143: added a way to return a list of apps the user has recently used.

src/terrain/clients/data_info.clj, src/terrain/clients/search.clj, src/terrain/routes.clj, src/terrain/routes/data.clj, src/terrain/routes/filesystem.clj, src/terrain/services/filesystem/directory.clj, src/terrain/util/transformers.clj
With these changes, in Sonora users should be able to browse community data, read files (textual and tabular), and search community data without logging in.  
Still To Do:
* View details - this involves the stats endpoint which can accept an array of paths and/or an array of UUIDs
* View metadata - requires a UUID
There was talk about converting all the data endpoints over to using paths instead of UUIDs and I didn't want to overlap with that effort.
=> CORE-1009 User can view community data without logging in

project.clj
This fixes a `stream closed` error that's intermittently occurring when we make calls to endpoints that return bare JSON arrays (that is, JSON arrays that aren't wrapped in an object).
=> CORE-1173: switched to a more recent version of clj-http

src/terrain/routes/schemas/dashboard_aggregator.clj
As mentioned, this is the partner PR to cyverse-de/dashboard-aggregator#7, just adding an optional key.
=> Add thumbnailUrl as added in cyverse-de/dashboard-aggregator#7

src/terrain/routes.clj, src/terrain/routes/filesystem/navigation.clj, src/terrain/services/filesystem/root.clj
Since sonora will no longer need to hit the data roots endpoint unauthenticated, I removed the logic for it.
=> Remove unauthd access to data roots endpoint

src/terrain/routes/schemas/vice.clj
Makes the keys in the ContainerStateTerminated schema optional because there seem to be various termination states where one or more of them could be omitted entirely. The startedAt and finishedAt values were made optionally a string since those were the specific fields the error report mentioned.
=> Loosen up the schema for ContainerStateTerminated

src/terrain/clients/data_info.clj, src/terrain/routes.clj, src/terrain/routes/filesystem/stats.clj, src/terrain/services/filesystem/directory.clj, src/terrain/services/filesystem/stat.clj
This should be the last change for CORE-1009 - allowing logged out users to browse public data
=> CORE-1009 Allow logged out users to use /filesystem/stat endpoint

project.clj, src/terrain/clients/notifications.clj, src/terrain/clients/notifications/raw.clj, src/terrain/services/admin.clj, src/terrain/util/config.clj, terrain.properties.tmpl, test-resources/notifications.json, test/terrain/notifications_test.clj, test/terrain/test_fixtures.clj
Integration tests can be painful to set up and tear down, and it's frequently beneficial to have a tighter feedback loop when code is being developed. This change defines a couple of test fixtures to make it easier to define unit tests involving code that makes calls to other services. It also provides an example unit test for future reference.
=> CORE-1180: add unit tests for an endpoint that makes calls to another service.

src/terrain/routes/filesystem/stats.clj, src/terrain/services/filesystem/stat.clj
The /filesystem/directory/create endpoint also uses this logic so the user param needs to be consistent
=> Revert do-stat to use add-current-user-to-map with no default user

src/terrain/routes.clj, src/terrain/routes/apps/categories.clj
Without this, it's possible for the /apps/hierarchies/:root-iri calls to match /apps/:system-id/:app-id instead
=> Rearrange app-ontology-routes prior to apps-routes

src/terrain/routes.clj, src/terrain/routes/apps/categories.clj, src/terrain/routes/apps/communities.clj, src/terrain/routes/apps/elements.clj, src/terrain/routes/apps/metadata.clj, src/terrain/routes/apps/pipelines.clj, src/terrain/routes/comments.clj
This should be the same order as before where all routes that came before `apps-routes` are now correctly before `apps-routes` again.  This is to workaround an issue where some fixed routes (e.g. /apps/hierarchies/:root-iri) are being caught by more dynamic routes (e.g. /apps/:system-id/:app-id)
=> Preserve ordering of all app routes

src/terrain/clients/app_exposer.clj, src/terrain/routes.clj, src/terrain/routes/instantlaunches.clj, src/terrain/routes/schemas/instantlaunch.clj, src/terrain/routes/schemas/instantlaunches.clj
Adds a single endpoint along with some schema definitions for instant launch support. This is what's expected to be needed for the basic proof-of-concept of instant launches (along with a whole bunch of unexposed backend API changes that have gone into app-exposer).
=> Instant Launch Proof-of-Concept

project.clj, src/terrain/clients/keycloak.clj, src/terrain/routes.clj, src/terrain/util/oauth.clj
This means that if terrain is set up with a proper tracer (usually, using the java autoinstrumentation), it'll create spans and send the trace parent information when it makes HTTP calls, as well as parse trace parents out of HTTP headers. I also added some specific spans for authentication-related code, mostly because when I was testing this I was curious where some time was going.
=> Add rudimentary opentelemetry instrumentation

project.clj
This PR is also tiny. I'm going to merge it immediately.
=> CORE-1216: bumped the common-swagger-api version

project.clj
This is just a dependency update, so I'm going to merge it immediately.
=> CORE-1219: switched to common-swagger-api version 3.0.7

src/terrain/clients/app_exposer.clj, src/terrain/routes.clj, src/terrain/routes/instantlaunches.clj, src/terrain/routes/schemas/instantlaunches.clj
All of this will be needed for administrating instant launches in Sonora. Adds the ability to manage the instant-launch to file mapping, along with the instant launch objects themselves.
=> Add more of the Instant Launch API

src/terrain/clients/app_exposer.clj, src/terrain/routes.clj, src/terrain/routes/schemas/vice.clj, src/terrain/routes/vice.clj
Requires that the changes in https://github.com/cyverse-de/app-exposer/pull/18 be merged. 
Contains the following changes:
* Proxies GET /vice/:host/description to the new call in app-exposer.
* Proxies GET /vice/:host/url-ready to the new call in app-exposer.
* Proxies GET /vice/resources to the call in app-exposer that filters based on the logged in user. Changed from the old version, which didn't validate access.
* Moves old VICE calls to under /vice/admin.
* Rearranges the use of (context) in the VICE routes file.
=> Loading Page API

src/terrain/clients/app_exposer.clj, src/terrain/routes/instantlaunches.clj, src/terrain/routes/schemas/instantlaunches.clj
Adds the `/admin/instant-launches/metadata/full` endpoint, which returns more information about the instant launch pulled from the quick launch and app information associated with it. Also includes the submission.
Adds the `/instant-launches/:id/full` endpoint, which returns the same information as the above endpoint, but just for a single instant launch.
These will allow us to get displayable, launchable instant launches in the UI without requiring multiple service calls to pull all of the necessary info together.
=> Add instant launch endpoints that contain submission info

src/terrain/routes/schemas/dashboard_aggregator.clj
Adds instant launches to the dashboard listing endpoint, but only for logged in users.
=> Add instantLaunches to the dashboard listing

src/terrain/clients/notifications.clj
I _think_ this is the last change regarding notifications and renaming communities to collections
=> Update email notification to call communities collections

src/terrain/clients/app_exposer.clj, src/terrain/routes.clj, src/terrain/routes/instantlaunches.clj
This endpoint is needed for [CORE-1484](https://cyverse.atlassian.net/browse/CORE-1484). It's a duplicate of the admin version of the endpoint except this one is for non-admins and is accessible to users who aren't logged in. This will allow the DE to query for the list of instant launches which have been added to the navigation drawer as a "first class" resource, specifically the `cli` instant launch.
=> CORE-1484 Add non-admin instant launch metadata search endpoint

k8s/terrain.yml, src/terrain/util/config.clj, src/terrain/util/jwt.clj
This PR makes the following changes:
1. Removes the explicit item names from the volume for the `signing-keys` secret.
2. Changes the mount point for the `signing-keys` secret.
3. Adds a volume and mount point for the new `accepted-keys` secret.
4. Updates the authentication code to log a message every time a legacy JWT token is used for authentication. This will allow us to determine whether or not this feature is being used and possibly remove support altogether at some point in the future.
The goal of this change is to make external deployments easier. External DE deployments currently must have custom deployment definitions for Terrain because they don't have the same set of accepted JWT signing keys. This change removes this requirement. Please see [CORE-1542][1] for details.
[1]: …
=> CORE-1542: updated the location of the signing keys for JWTs

src/terrain/routes/schemas/permanent_id_requests.clj
This PR will update the `PermanentIDRequestBase` schema to allow `null` folder values in (/admin)/permanent-id-requests listing responses.
=> CORE-1603 Allow null folder values in DOI Request listing responses

src/terrain/clients/data_usage_api.clj, src/terrain/routes.clj, src/terrain/routes/data_usage_api.clj, src/terrain/routes/schemas/data_usage_api.clj, src/terrain/util/config.clj
For now this is the only one, but I wanted to get it pushed up now so it's easier to be integrating in the UI.
=> CORE-1930: Add initial data-usage-api route

project.clj
Updates the version of common-swagger-api listed in project.clj to 3.2.3, which should allow analysis submissions to include the :max_cpu_cores field.
=> Update the version of common-swagger-api to 3.2.3

src/terrain/clients/resource_usage_api.clj, src/terrain/routes/resource_usage_api.clj, src/terrain/routes/schemas/resource_usage_api.clj
Adds the initial version of the `/resource-usage/summary` route.  Information about the user's plan, analyses numbers, etc. will be added later. This currently gets the route in place along with the schema and returns the cpu and data usage.
=> Add /resource-usage/summary route

project.clj, src/terrain/routes/schemas/instantlaunches.clj
This PR updates terrain with the latest schema changes for app versions from cyverse-de/common-swagger-api#75, and also updates the `FullInstantLaunch` schema with an `app_version_id` field, required due to changes in cyverse-de/app-exposer#44.
=> CORE-316 Update endpoint schemas for app versions

src/terrain/routes/schemas/vice.clj
I can't find a good way to test this in QA, but this appears to be the field that is causing issues in production. Apparently there is a way for it to be missing.
=> Make the reason field optional in the waiting state object

project.clj, src/terrain/clients/apps/raw.clj, src/terrain/routes.clj, src/terrain/routes/apps/admin/apps.clj, src/terrain/routes/apps/pipelines.clj, src/terrain/routes/apps/versions.clj
This PR will add new CRUD endpoints for app versions:
* `POST /apps/:system-id/:app-id/versions`
* `DELETE /apps/:system-id/:app-id/versions/:version-id`
* `GET /apps/:system-id/:app-id/versions/:version-id`
* `PATCH /apps/:system-id/:app-id/versions/:version-id`
* `PUT /apps/:system-id/:app-id/versions/:version-id`
* `POST /apps/:system-id/:app-id/versions/:version-id/copy`
* `GET /apps/:system-id/:app-id/versions/:version-id/details`
* `GET /apps/:system-id/:app-id/versions/:version-id/documentation`
* `PATCH /apps/:system-id/:app-id/versions/:version-id/documentation`
* `POST /apps/:system-id/:app-id/versions/:version-id/documentation`
* `GET /apps/:system-id/:app-id/versions/:version-id/integration-data`
* `GET /apps/:system-id/:app-id/versions/:version-id/tasks`
* `GET …
=> CORE-316 Add app version endpoints

src/terrain/routes/schemas/instantlaunches.clj
This PR will add the  `app_version` label to the `FullInstantLaunch` response schema, and must be merged after cyverse-de/app-exposer#51.
=> CORE-1809 Add app_version label to FullInstantLaunch schema

src/terrain/clients/qms.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj
The primary purpose of adding this endpoint is to add validation to the Terrain CLI. Here are the Swagger docs for the endpoint:
The usage of this endpoint is very simple:
```
$ curl -sH "$AUTH_HEADER" "http://localhost:8000/terrain/qms/resource-types" | jq
{
"result": [
{
"id": "99e3bc7e-950a-11ec-84a4-406c8f3e9cbb",
"name": "cpu.hours",
"unit": "cpu hours"
},
{
"id": "99e3f91e-950a-11ec-84a4-406c8f3e9cbb",
"name": "data.size",
"unit": "bytes"
}
],
"status": "OK"
}
```
=> CORE-1835: add an endpoint for listing resource types

src/terrain/clients/coge.clj, src/terrain/clients/qms.clj, src/terrain/clients/util.clj
This change standardizes the error response bodies from all QMS endpoints in Terrain so that they more closely resemble error response bodies from other endpoints in Terrain, for example:
Before:
```
$ curl -sH "$AUTH_HEADER" "https://qa.cyverse.org/terrain/admin/qms/users/sarahr/plan/does.not.exist/quota" -H 'Content-Type: application/json' -d '{"quota":10000}' | jq
{
"error": "resource type 'does.not.exist' not found",
"status": "Bad Request"
}
```
After:
```
$ curl -sH "$AUTH_HEADER" "http://localhost:8000/terrain/admin/qms/users/sarahr/plan/does.not.exist/quota" -H 'Content-Type: application/json' -d '{"quota":10000}' | jq
{
"error_code": "ERR_BAD_REQUEST",
"reason": "resource type 'does.not.exist' not found"
}
```
=> CORE-1834: standardize error responses from QMS endpoints

src/terrain/clients/qms.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj
This change adds the paid subscription plans to the subscription creation and retrieval endpoints in `terrain`. For the subscription retrieval endpoints, the change consists of a new field in the response body. For the creation endpoints, the change includes new required fields.
For the `POST /terrain/admin/qms/subscriptions` endpoint, each subscription request must now contain a `paid` flag indicating whether or not the user paid for the subscription. Here's an example request body:
```
{
"subscriptions": [
{
"username": "sarahr",
"plan_name": "Commercial",
"paid": false
}
]
}
```
For the `PUT /terrain/admin/qms/users/{username}/plan/{plan-name}` endpoint, a new required query parameter was added.
=> CORE-1840: add support for the paid subscription flag

project.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj, src/terrain/services/qms.clj, src/terrain/util/config.clj
This PR adds the ability to do the following to subscription add-ons as an administrator:
* Apply add-ons to a subscription.
* Modify subscription add-ons.
* Get information about a subscription add-on.
* List subscription add-ons.
* Delete subscription add-ons.
The add, delete, and update operations will change the quota for the resource type mentioned in the add-on. That logic lives in the `subscriptions` service.
JIRAs affected:
* https://cyverse.atlassian.net/browse/CORE-1845
* https://cyverse.atlassian.net/browse/CORE-1846
* https://cyverse.atlassian.net/browse/CORE-1847
* https://cyverse.atlassian.net/browse/CORE-1848
=> Admin endpoints for the subscription add-on functionality.

project.clj, src/terrain/services/filesystem/common_paths.clj, src/terrain/services/filesystem/sharing.clj
This PR will also update calls to `clj-jargon.item-info/trash-base-dir`, which no longer requires a user param, so that items can be put into the same trash paths as used by `irm`.
=> CORE-1893 Update clj-jargon to v3.1.0

project.clj, src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj
This change introduces a couple of new concepts: Subscription Periods, and consumable resource types.
A subscription period refers to the period of time during which the subscription is active. All of our subscriptions are active for one year by default, so a single subscription period is equivalent to one year. With this change, a user may purchase a subscription for multiple subscription periods. For example, if a user chooses to purchase a three year subscription, the user would be given access to the allocations associated with their subscription for three years.
A consumable resource type is a type of resource is not reclaimable. For example, CPU hours can't be reclaimed because once a unit of compute time has been used, it can never be used again. Conversely, storage space can be …
=> CORE-1983: add support for multiyear subscriptions

src/terrain/routes/qms.clj, src/terrain/routes/schemas/qms.clj
- Added support for the new query parameters to the service account endpoint for granting subscriptions.
- Also found and fixed a bug involving support for the `end-date` query parameter.
=> CORE-1983: service account support for multiyear subscriptions.

project.clj
A newer version of `slf4j-api` was being included by a transitive dependency, which broke logging. I added the explicit dependency to fix logging until we can officially migrate to the newer version.
=> DD-18: added a direct dependency on the slf4j API

src/terrain/routes.clj, src/terrain/routes/filesystem.clj, src/terrain/util/transformers.clj
This PR will add the `secured-filesystem-metadata-routes` to the `optionally-authenticated-routes`, allowing them to be accessed without the `/secured` prefix, and allowing `anonymous` access for the GET endpoints.
POST and CSV download endpoints still require authentication.
This is required in order for Local Contexts Labels and Notices to be viewed by logged out users for public data under Community Data folders.
=> CORE-1967 Allow anonymous access in /filesystem/metadata endpoints

src/terrain/routes/schemas/bootstrap.clj, src/terrain/services/bootstrap.clj
(also, bring back the proper schemas for preferences, now that we know what was actually going on there, namely that the presence of an `:error` key in stored preferences was changing the schema to the error one, ironically, in error)
=> Trim the :error key in preferences when other keys are present

src/terrain/util/keycloak_oidc.clj
I did a rebase and failed to do another lint check before merging the last PR. This PR fixes a lint error that was reintroduced by the rebase.
=> CORE-2013: fixed an import error

src/terrain/clients/app_exposer.clj, src/terrain/routes/instantlaunches.clj
pairs with cyverse-de/app-exposer#70
=> passthrough endpoints for new instant launch non-admin & updating paths for admin

.clj-kondo/config.edn, project.clj, src/terrain/clients/apps/raw.clj, src/terrain/clients/keycloak/admin.clj, src/terrain/clients/qms/model.clj, src/terrain/clients/qms_nats.clj, src/terrain/routes/bootstrap.clj, src/terrain/routes/schemas/qms.clj, src/terrain/services/bootstrap.clj, src/terrain/util/config.clj, src/terrain/util/nats.clj, test/terrain/qms_model.clj
The primary reason for this change is to allow us to schedule rate and default quota limit changes for the future so that they automatically become active at a time that we specify. For example, we currently have some rate and default quota limit changes planned for January 1st, but we don't want to have to log in on New Years Day to make the changes. Having scheduled changes in the system means that we can set up the changes in advance and let them become effective later.
=> CORE-2016: support for scheduled quota default and subscription rate changes.

src/terrain/routes/schemas/qms.clj
The `consumable` flag shouldn't have been added to the resource type for an addon update.
=> CORE-2016: removed the unnecessary `consumable` flag from addon updates

skaffold.yaml
The primary purpose of this is to allow the platform to be specified for cross-compilation.
=> update the Skaffold schema version to v3

project.clj, src/terrain/clients/metadata/raw.clj, src/terrain/routes/filesystem.clj
This PR will add a `GET /filesystem/metadata` endpoint, which allows a client to search file and folder metadata AVUs by a set of attributes, values, units, and target-ids.
It also will add a `POST /filesystem/metadata/search` endpoint, which does the same thing, only it accepts search params in the request body instead, calling the new `metadata-client.core/search-avus` method.
This is currently restricted to only searching the DE's metadata database, and not iRODS AVUs.
This PR depends on cyverse-de/metadata-client#7 and cyverse-de/common-swagger-api#90 which should be merged before this PR.
=> CORE-2034 Search metadata by `target-ids`

k8s/terrain.yml
Most of these changes are just whitespace. The relevant change is that I removed the time zone data mounts and added the `TZ` environment variable instead.
=> CORE-2074: removed time zone data mounts.

CLAUDE.md, k8s/terrain.yml, src/terrain/routes.clj, src/terrain/routes/email.clj, src/terrain/routes/schemas/email.clj, src/terrain/services/email.clj, src/terrain/util/config.clj, src/terrain/util/email.clj
The primary purpose of this PR is to add an endpoint that the Subscription Portal can use to send emails to users on behalf of CyVerse. We wanted this endpoint to be fairly secure, so the `cyverse-emailer` role has to be associated with the account in order for calls to this endpoint to succeed.
The test is fairly simple. The first step is to obtain an access token for the service account:
``` bash
$ export AUTH_HEADER="Authorization: Bearer $(curl -su "$CLIENT_ID:$CLIENT_SECRET" https://kc.cyverse.org/auth/realms/CyVerse/protocol/openid-connect/token -d grant_type=client_credentials | jq -r .access_token)"
```
**Note:** I was testing against production because I know that emails from production are working. If I had been testing against the QA environment then the Keycloak realm would …
=> CORE-2086: added a service-account endpoint for sending emails.

src/terrain/routes/schemas/email.clj, src/terrain/services/email.clj, src/terrain/util/email.clj
The purpose of this change is to allow the subscription portal to send courtesy copies of emails to CyVerse so that we have a record of the email.
=> CORE-2086: add support for `CC` and `BCC` email headers.
